/* Technical fixtures on owned local services; no human participants. */
const {chromium}=require('playwright');const fs=require('fs');const path=require('path');const assert=require('assert/strict');
const ui=process.env.ACCEPTANCE_UI_URL,api=process.env.ACCEPTANCE_API_URL,out=process.env.ACCEPTANCE_OUTPUT;
for(const url of [ui,api])assert(['localhost','127.0.0.1'].includes(new URL(url).hostname));
const result={checks:[],page_errors:[]};let browser;
async function login(role){const page=await browser.newPage();page.on('pageerror',e=>result.page_errors.push(e.message));await page.goto(ui+'/login');await page.locator('input[type=email]').fill(role+'@learnflow.com');await page.locator('input[type=password]').fill(process.env.ACCEPTANCE_FIXTURE_PASSWORD);await page.getByRole('button',{name:'🚀 开始冒险'}).click();await page.waitForURL('**/'+role);return page;}
(async()=>{
 browser=await chromium.launch({headless:true,...(process.env.ACCEPTANCE_CHROME?{executablePath:process.env.ACCEPTANCE_CHROME}:{})});
 const teacher=await login('teacher');await teacher.getByRole('button',{name:'作业布置与提交记录',exact:true}).click();await teacher.waitForURL('**/teacher/assign');await teacher.locator('select').first().selectOption('assignment-class');await teacher.getByRole('button',{name:/作业验收知识点/}).click();await teacher.locator('input[type=datetime-local]').fill('2026-12-01T12:00');const assigned=teacher.waitForResponse(r=>r.url()===api+'/teacher/assignments'&&r.request().method()==='POST');await teacher.getByRole('button',{name:'布置作业',exact:true}).click();const response=await assigned;assert.equal(response.status(),200);const assignmentId=(await response.json()).assignment_id;result.checks.push('teacher_assigns_curriculum_task_through_ui');
 const student=await login('student');await student.goto(ui+'/student/assignments');await student.getByRole('button',{name:'查看作业题目',exact:true}).click();await student.locator('.math-content .katex').first().waitFor();let fail=true;await student.route('**/student/assignments/*/answer',route=>fail?route.abort('failed'):route.continue());await student.getByLabel('作业答案',{exact:true}).fill('0');await student.getByRole('button',{name:'提交作业答案',exact:true}).click();await student.getByRole('alert').filter({hasText:'提交未确认'}).waitFor();assert.equal(await student.getByText('本题作业答案已记录。',{exact:true}).count(),0);result.checks.push('network_failure_preserves_unconfirmed_answer');fail=false;
 const saved=student.waitForResponse(r=>r.url()===api+'/student/assignments/'+assignmentId+'/answer'&&r.request().method()==='POST');await student.getByRole('button',{name:'提交作业答案',exact:true}).click();assert.equal((await saved).status(),200);await student.getByText('回答有误',{exact:true}).waitFor();await student.getByText('本题作业答案已记录。',{exact:true}).waitFor();await student.reload();await student.getByRole('button',{name:'查看作业题目',exact:true}).click();await student.getByText('本题作业答案已记录。',{exact:true}).waitFor();assert.equal(await student.getByRole('button',{name:'提交作业答案',exact:true}).count(),0);result.checks.push('server_grade_and_assignment_submission_survive_reload');
 await teacher.getByLabel('选择作业',{exact:true}).selectOption(assignmentId);const table=teacher.locator('table');await table.locator('tbody tr').first().waitFor();const cells=await table.locator('tbody tr').first().locator('td').allTextContents();assert.equal(cells[1],'1');assert.equal(cells[2],'0');assert.equal(cells[3],'0%');await teacher.getByRole('button',{name:'刷新提交记录',exact:true}).click();await table.locator('tbody tr').first().waitFor();assert.equal(await teacher.getByLabel('选择作业',{exact:true}).inputValue(),assignmentId);result.checks.push('teacher_reads_explicit_submission_and_refresh_keeps_selection');
 await student.getByText('全部已提交',{exact:true}).waitFor();
 assert.equal(cells[5],'全部已提交');
 await teacher.getByRole('button',{name:/作业验收知识点/}).click();await teacher.locator('input[type=datetime-local]').fill('2026-12-02T12:00');await teacher.getByLabel('重新布置为新版本（不继承旧提交）',{exact:true}).check();const reassigned=teacher.waitForResponse(r=>r.url()===api+'/teacher/assignments'&&r.request().method()==='POST');await teacher.getByRole('button',{name:'布置作业',exact:true}).click();assert.equal((await reassigned).status(),200);await teacher.getByLabel('选择作业',{exact:true}).selectOption(assignmentId);await table.locator('tbody tr').first().waitFor();assert.equal((await table.locator('tbody tr').first().locator('td').allTextContents())[1],'0');
 await teacher.getByLabel('结果版本',{exact:true}).selectOption({label:'版本 1 · 1 题'});await table.getByText('全部已提交',{exact:true}).waitFor();assert.equal((await table.locator('tbody tr').first().locator('td').allTextContents())[1],'1');result.checks.push('new_version_starts_empty_and_teacher_can_read_old_submission');
 await student.getByRole('button',{name:'刷新题目与版本',exact:true}).click();await student.getByLabel('作业答案',{exact:true}).waitFor();await student.getByText('版本 2 · 已提交 0/1 道',{exact:true}).waitFor();result.checks.push('student_refreshes_to_new_version_without_inheriting_old_completion');
 await teacher.evaluate(() => window.scrollTo(0,0));await student.evaluate(() => window.scrollTo(0,0));
 await teacher.screenshot({path:path.join(out,'teacher_assignment_results.png'),fullPage:true});await student.screenshot({path:path.join(out,'student_assignment_submitted.png'),fullPage:true});assert.deepEqual(result.page_errors,[]);result.passed=true;
})().catch(e=>{result.passed=false;result.failure=e.stack;process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(out,'assignments_results.json'),JSON.stringify(result,null,2));if(browser)await browser.close();console.log(JSON.stringify(result));});
