/* Syntax/renderability audit of public content, not item correctness or calibration. */
const fs=require('fs');const path=require('path');const crypto=require('crypto');const assert=require('assert/strict');
const root=path.resolve(__dirname,'../..');const ts=require(root+'/learnflow-frontend/node_modules/typescript');const katex=require(root+'/learnflow-frontend/node_modules/katex');
const tokenizer=root+'/learnflow-frontend/src/components/content/mathContent.ts';const bankPath=root+'/results/k12/xes_question_bank.json';
const compiled=ts.transpileModule(fs.readFileSync(tokenizer,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;
const m={exports:{}};new Function('exports','require','module',compiled)(m.exports,require,m);const split=m.exports.splitMathContent;
const cases=['普通题干','求解 $$x+3=10$$。','分数 $\\frac{1}{2}$，换行\n不丢失。','显示\\[x^2\\]，行内\\(x\\)。','价格\\$5','未闭合 $$x+3','原文 <img src=x onerror=alert(1)>'];
for(const text of cases)assert.equal(split(text).map(p=>p.raw).join(''),text);
assert.equal(split('价格\\$5').filter(p=>p.kind==='math').length,0);assert.equal(split('显示\\[x^2\\]')[1].display,true);
const items=JSON.parse(fs.readFileSync(bankPath)).items.filter(x=>x.numeric_app_compatible);let total=0,rendered=0;const errors=[],warnings=[],review=[];
for(const item of items){assert.equal(split(item.content).map(p=>p.raw).join(''),item.content);if(/下表|表格|表中|下图|如图/.test(item.content))review.push({task_id:item.task_id,reason:'source_mentions_table_or_figure_requires_content_review'});
for(const part of split(item.content)){if(part.kind!=='math')continue;total++;try{katex.renderToString(part.value,{displayMode:part.display,throwOnError:true,trust:false,maxSize:10,maxExpand:1000,output:'htmlAndMathml',macros:{},strict:code=>{warnings.push({task_id:item.task_id,code});return 'ignore';}});rendered++;}catch(e){errors.push({task_id:item.task_id,source:part.raw,error:e.message});}}}
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const result={katex_version:katex.version,compatible_items:items.length,math_segments:total,rendered_segments:rendered,syntax_errors:errors,strict_warnings:warnings,strict_warning_item_count:new Set(warnings.map(x=>x.task_id)).size,content_review_flags:review,splitter_cases_passed:cases.length,source_hashes:{tokenizer:sha(tokenizer),renderer:sha(root+'/learnflow-frontend/src/components/content/MathContent.tsx'),package_lock:sha(root+'/learnflow-frontend/package-lock.json'),bank:sha(bankPath)},scope:'Delimited formula syntax only. No HTML/table reconstruction, image support, expert item review, correctness or calibrated difficulty.'};
const out=process.argv[2];assert(out,'Provide output JSON path');fs.mkdirSync(path.dirname(path.resolve(out)),{recursive:true});fs.writeFileSync(out,JSON.stringify(result,null,2));console.log(JSON.stringify({items:items.length,math_segments:total,rendered,errors:errors.length,warnings:warnings.length,review_flags:review.length}));
