/* Run only against a disposable local database; never use real accounts. */
const {chromium}=require('playwright');
const fs=require('fs');const path=require('path');const assert=require('assert/strict');
const ui=process.env.ACCEPTANCE_UI_URL||'http://127.0.0.1:15173';
const api=process.env.ACCEPTANCE_API_URL||'http://127.0.0.1:18800/api/v1';
for(const url of [ui,api])assert(['127.0.0.1','localhost','[::1]'].includes(new URL(url).hostname),'Local disposable services required');
const password=process.env.ACCEPTANCE_FIXTURE_PASSWORD;assert(password,'Set ACCEPTANCE_FIXTURE_PASSWORD for isolated seed accounts');
const out=process.env.ACCEPTANCE_OUTPUT;assert(out,'Set ACCEPTANCE_OUTPUT');fs.mkdirSync(out,{recursive:true});
const result={checks:[],page_errors:[],started_at:new Date().toISOString()};
const topic='acceptance-'+Date.now();const approvedTitle=topic+'-approve',rejectedTitle=topic+'-reject';
let browser;
async function login(role){const context=await browser.newContext();const page=await context.newPage();page.on('pageerror',e=>result.page_errors.push({role,message:e.message}));await page.goto(ui+'/login');await page.locator('input[type=email]').fill(role+'@learnflow.com');await page.locator('input[type=password]').fill(password);await page.getByRole('button',{name:'🚀 开始冒险'}).click();await page.waitForURL('**/'+role);return {context,page};}
async function request(session,route){const token=await session.page.evaluate(()=>localStorage.getItem('access_token'));return session.context.request.get(api+route,{headers:{Authorization:'Bearer '+token}});}
(async()=>{
 browser=await chromium.launch({headless:true,...(process.env.ACCEPTANCE_CHROME?{executablePath:process.env.ACCEPTANCE_CHROME}:{})});
 const teacher=await login('teacher');await teacher.page.getByRole('button',{name:'创建题目',exact:true}).click();const ids=[];
 for(const title of [approvedTitle,rejectedTitle]){await teacher.page.getByPlaceholder('标题',{exact:true}).fill(title);await teacher.page.getByPlaceholder('题目内容').fill('求解 $$x + \\frac{3}{1} = 10$$，填写 x。');await teacher.page.getByPlaceholder('知识点/主题').fill(topic);await teacher.page.getByPlaceholder('正确答案').fill('7');await teacher.page.getByPlaceholder('解析（可选）').fill('Subtract 3 from both sides: x = 7.');await teacher.page.locator('.math-content .mfrac').first().waitFor();const saved=teacher.page.waitForResponse(r=>r.url()===api+'/teacher/tasks'&&r.request().method()==='POST');await teacher.page.getByRole('button',{name:'提交审核',exact:true}).click();const response=await saved;assert.equal(response.status(),200);ids.push((await response.json()).id);await teacher.page.getByText('题目已创建，等待管理员审核',{exact:true}).waitFor();}
 result.checks.push('teacher_creates_two_pending_items_through_ui');
 const student=await login('student');assert.equal((await request(student,'/student/next-task?topic='+topic)).status(),404);result.checks.push('pending_items_not_delivered');
 const admin=await login('admin');await admin.page.getByRole('button',{name:'内容审核',exact:true}).click();
 for(const [title,decision] of [[approvedTitle,'通过'],[rejectedTitle,'拒绝']]){const card=admin.page.getByText(title,{exact:true}).locator('xpath=../../..');await card.getByText('正确答案：7',{exact:true}).waitFor();await card.getByText('解析：Subtract 3 from both sides: x = 7.',{exact:true}).waitFor();const reviewed=admin.page.waitForResponse(r=>r.url()===api+'/admin/review-task'&&r.request().method()==='POST');await card.getByRole('button',{name:decision,exact:true}).click();assert.equal((await reviewed).status(),200);await admin.page.getByText(title,{exact:true}).waitFor({state:'detached'});}
 const statuses=await(await request(teacher,'/teacher/tasks')).json();assert.equal(statuses.find(t=>t.id===ids[0]).review_status,'approved');assert.equal(statuses.find(t=>t.id===ids[1]).review_status,'rejected');result.checks.push('approval_and_rejection_persist_and_leave_queue');
 await teacher.page.goto(ui+'/teacher');await teacher.page.getByText(approvedTitle,{exact:true}).locator('xpath=..').filter({hasText:'已通过'}).waitFor();await teacher.page.getByText(rejectedTitle,{exact:true}).locator('xpath=..').filter({hasText:'已拒绝'}).waitFor();await teacher.page.screenshot({path:path.join(out,'teacher_review_status.png'),fullPage:true});result.checks.push('teacher_can_read_review_status_in_ui');
 const selected=await(await request(student,'/student/next-task?topic='+topic)).json();assert.equal(selected.task.id,ids[0]);assert(!('correct_answer' in selected.task));result.checks.push('approved_item_available_without_answer_leak');
 await student.page.route('**/student/next-task*',route=>{const url=new URL(route.request().url());url.searchParams.set('topic',topic);return route.continue({url:url.href});});
 await student.page.goto(ui+'/student/learn');await student.page.getByPlaceholder('输入你的答案...').fill('7');await student.page.locator('.math-content .mfrac').first().waitFor();result.checks.push('fraction_rendered_in_alternate_learning_route');
 async function submit(value,expected){await student.page.getByPlaceholder('输入你的答案...').fill(value);const response=student.page.waitForResponse(r=>r.url()===api+'/student/submit-answer'&&r.request().method()==='POST');await student.page.getByRole('button',{name:'提交答案',exact:true}).click();const r=await response;assert.equal(r.status(),200);assert.equal((await r.json()).is_correct,expected);await student.page.getByRole('button',{name:'下一题',exact:true}).waitFor();}
 await submit('7',true);await student.page.getByRole('button',{name:'下一题',exact:true}).click();await submit('__wrong_fixture_answer__',false);result.checks.push('learning_session_server_grades_correct_and_wrong');
 await student.page.getByRole('button',{name:/看.*讲解|看看关键步骤/}).click();await student.page.getByText('Subtract 3 from both sides: x = 7.',{exact:true}).waitFor();result.checks.push('tutorial_visible_without_automatic_skip');
 await student.page.getByRole('button',{name:/再试一次/}).click();await student.page.getByPlaceholder('输入你的答案...').waitFor();
 let fail=true;await student.page.route('**/student/submit-answer',route=>fail?route.abort('failed'):route.continue());await student.page.getByPlaceholder('输入你的答案...').fill('7');await student.page.getByRole('button',{name:'提交答案',exact:true}).click();await student.page.getByRole('alert').filter({hasText:'答案尚未确认保存'}).waitFor();assert.equal(await student.page.getByRole('button',{name:'下一题',exact:true}).count(),0);fail=false;await submit('7',true);result.checks.push('failed_submission_visible_and_retry_succeeds');
 await student.page.screenshot({path:path.join(out,'learning_feedback.png'),fullPage:true});
 let failNext=true;await student.page.route('**/student/next-task*',route=>failNext?route.abort('failed'):route.fallback());await student.page.goto(ui+'/student/learn');await student.page.getByRole('heading',{name:'任务加载失败',exact:true}).waitFor();failNext=false;await student.page.getByRole('button',{name:'重试',exact:true}).click();await student.page.getByPlaceholder('输入你的答案...').waitFor();result.checks.push('failed_task_request_recovers_without_unhandled_rejection');
 const stats=await(await request(admin,'/admin/stats')).json();assert.equal(stats.total_attempts,3);result.checks.push('only_three_successful_submissions_persisted');
 await student.page.goto(ui+'/learn');await student.page.getByPlaceholder('输入你的答案...').waitFor();await student.page.locator('.math-content .mfrac').first().waitFor();await student.page.getByLabel('题目难度等级 5/10',{exact:true}).waitFor();assert.equal(await student.page.getByText(/心流区/).count(),0);await student.page.setViewportSize({width:390,height:844});await student.page.screenshot({path:path.join(out,'learn_math_mobile.png'),fullPage:true});assert(await student.page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));result.checks.push('fraction_rendered_in_main_learning_route_without_mobile_overflow');assert.deepEqual(result.page_errors,[]);result.passed=true;
})().catch(e=>{result.passed=false;result.failure=e.stack;process.exitCode=1;}).finally(async()=>{result.finished_at=new Date().toISOString();fs.writeFileSync(path.join(out,'content_learning_results.json'),JSON.stringify(result,null,2));if(browser)await browser.close();console.log(JSON.stringify(result));});
