const {chromium}=require('playwright');const fs=require('fs');const path=require('path');const assert=require('assert/strict');
const ui=process.env.ACCEPTANCE_UI_URL,api=process.env.ACCEPTANCE_API_URL,out=process.env.ACCEPTANCE_OUTPUT;for(const url of [ui,api])assert(['localhost','127.0.0.1'].includes(new URL(url).hostname));
const result={checks:[],page_errors:[]};let browser;
(async()=>{browser=await chromium.launch({headless:true,...(process.env.ACCEPTANCE_CHROME?{executablePath:process.env.ACCEPTANCE_CHROME}:{})});const p=await browser.newPage();p.on('pageerror',e=>result.page_errors.push(e.message));await p.goto(ui+'/login');await p.locator('input[type=password]').fill(process.env.ACCEPTANCE_FIXTURE_PASSWORD);await p.getByRole('button',{name:'🚀 开始冒险'}).click();await p.waitForURL('**/student');await p.getByText('到期复习',{exact:true}).click();await p.waitForURL('**/student/reviews');await p.getByPlaceholder('输入复习答案...').waitFor();await p.locator('.math-content .katex').first().waitFor();result.checks.push('dashboard_enters_due_review_and_renders_question');
let fail=true;await p.route('**/student/reviews/*/answer',r=>fail?r.abort('failed'):r.continue());await p.getByPlaceholder('输入复习答案...').fill('x = 7');await p.getByRole('button',{name:'提交复习答案',exact:true}).click();await p.getByRole('alert').filter({hasText:'复习尚未确认完成'}).waitFor();assert.equal(await p.getByText('本次复习回答正确。',{exact:true}).count(),0);result.checks.push('failed_review_submission_stays_uncompleted_in_ui');fail=false;
const saved=p.waitForResponse(r=>r.url().includes('/reviews/acceptance-review-row/answer')&&r.request().method()==='POST');await p.getByRole('button',{name:'提交复习答案',exact:true}).click();const response=await saved;assert.equal(response.status(),200);const data=await response.json();assert.equal(data.is_correct,true);await p.getByText('本次复习回答正确。',{exact:true}).waitFor();await p.getByText('当前有 0 道到期复习 · review-fixture',{exact:true}).waitFor();await p.getByText('题目讲解',{exact:true}).waitFor();await p.screenshot({path:path.join(out,'review_feedback.png'),fullPage:true});result.checks.push('server_grades_review_and_returns_next_schedule');
const token=await p.evaluate(()=>localStorage.getItem('access_token'));const headers={Authorization:'Bearer '+token};const repeated=await p.request.post(api+'/student/reviews/acceptance-review-row/answer',{headers,data:{answer:'7'}});assert.equal(repeated.status(),409);result.checks.push('completed_review_rejects_second_submission');
await p.getByRole('button',{name:'继续复习',exact:true}).click();await p.getByText('当前没有到期复习。',{exact:true}).waitFor();await p.getByRole('button',{name:'返回学生首页',exact:true}).click();await p.getByText('当前没有到期复习',{exact:true}).waitFor();const dashboard=await(await p.request.get(api+'/student/dashboard',{headers})).json();assert.equal(dashboard.pending_reviews,0);assert.equal(dashboard.today.total_attempts,1);result.checks.push('completed_review_leaves_queue_and_dashboard_updates');assert.deepEqual(result.page_errors,[]);result.passed=true;
})().catch(e=>{result.passed=false;result.failure=e.stack;process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(out,'reviews_results.json'),JSON.stringify(result,null,2));if(browser)await browser.close();console.log(JSON.stringify(result));});
